server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 아이디
    password: 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://database-1.cgpr3ybkrki6.ap-northeast-2.rds.amazonaws.com:3306/everytime 
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # 조심하자!! 젭알 ㅠ
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

file:
  path: /home/ubuntu/upload